# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21b036eaad8985e6e9c0f0b7340b5e1f27a63e133186a0d3082f8e459657223e772d07f5112bd46487e046ccd5e8134ade7e08d615591ef5762a993d066b3bf5

test:
  secret_key_base: 26e2d7a72c76d6af9ed3117a79d94ae819ee77471285ddc03a24a575bb958cf22d6df400bb45e6ea4e22b426f27dd4c46c19f3d7fe4ea7f85ebafb8c778ada2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
